# Micro-Credit Defaulter prediction Model Project

## Flip Robo Technologies  

## Project - 3

### Micro credit defaulter prediction model

> Dataset primarily belongs to telecom industry where 

> In this project we analyze the data and create a machine learning model which to predict the customer payment within 5 days or default. Target/label column is named as label with two values '1' for loan payed and '0' for default. This is a classification problem

In [1]:
# importing the libraries

#EDA and preprocessing
import numpy as np
import pandas as pd
import scipy as stats
import os

#Data Visualisation
import seaborn as sns
import matplotlib.pyplot as plt

#Warnings
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [3]:
#Importing the dataset

data=pd.read_csv('D:\Krsna\Internship\Data file.csv')
data

,Unnamed: 0,label,msisdn,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,...,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90,pcircle,pdate
0,1,0,21408I70789,272.0,3055.050000,3065.150000,220.13,260.13,2.0,0.0,...,6.0,0.0,2.0,12,6,0.0,29.000000,29.000000,UPW,2016-07-20
1,2,1,76462I70374,712.0,12122.000000,12124.750000,3691.26,3691.26,20.0,0.0,...,12.0,0.0,1.0,12,12,0.0,0.000000,0.000000,UPW,2016-08-10
2,3,1,17943I70372,535.0,1398.000000,1398.000000,900.13,900.13,3.0,0.0,...,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000,UPW,2016-08-19
3,4,1,55773I70781,241.0,21.228000,21.228000,159.42,159.42,41.0,0.0,...,6.0,0.0,2.0,12,6,0.0,0.000000,0.000000,UPW,2016-06-06
4,5,1,03813I82730,947.0,150.619333,150.619333,1098.90,1098.90,4.0,0.0,...,6.0,0.0,7.0,42,6,0.0,2.333333,2.333333,UPW,2016-06-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209588,209589,1,22758I85348,404.0,151.872333,151.872333,1089.19,1089.19,1.0,0.0,...,6.0,0.0,2.0,12,6,0.0,1.000000,1.000000,UPW,2016-06-17
209589,209590,1,95583I84455,1075.0,36.936000,36.936000,1728.36,1728.36,4.0,0.0,...,6.0,0.0,3.0,18,6,0.0,1.000000,1.000000,UPW,2016-06-12
209590,209591,1,28556I85350,1013.0,11843.111667,11904.350000,5861.83,8893.20,3.0,0.0,...,12.0,0.0,6.0,54,12,0.0,4.000000,3.833333,UPW,2016-07-29
209591,209592,1,59712I82733,1732.0,12488.228333,12574.370000,411.83,984.58,2.0,38.0,...,12.0,0.0,3.0,24,12,0.0,0.000000,10.500000,UPW,2016-07-25
209592,209593,1,65061I85339,1581.0,4489.362000,4534.820000,483.92,631.20,13.0,0.0,...,12.0,0.0,2.0,18,12,0.0,0.000000,0.000000,UPW,2016-07-07

#### Column description and information

Slno	Variable	Definition	Comment
1	label	Flag indicating whether the user paid back the credit amount within 5 days of issuing the loan{1:success, 0:failure}	
2	msisdn	mobile number of user	
3	aon	age on cellular network in days	
4	daily_decr30	Daily amount spent from main account, averaged over last 30 days (in Indonesian Rupiah)	
5	daily_decr90	Daily amount spent from main account, averaged over last 90 days (in Indonesian Rupiah)	
6	rental30	Average main account balance over last 30 days	Unsure of given definition
7	rental90	Average main account balance over last 90 days	Unsure of given definition
8	last_rech_date_ma	Number of days till last recharge of main account	
9	last_rech_date_da	Number of days till last recharge of data account	
10	last_rech_amt_ma	Amount of last recharge of main account (in Indonesian Rupiah)	
11	cnt_ma_rech30	Number of times main account got recharged in last 30 days	
12	fr_ma_rech30	Frequency of main account recharged in last 30 days	Unsure of given definition
13	sumamnt_ma_rech30	Total amount of recharge in main account over last 30 days (in Indonesian Rupiah)	
14	medianamnt_ma_rech30	Median of amount of recharges done in main account over last 30 days at user level (in Indonesian Rupiah)	
15	medianmarechprebal30	Median of main account balance just before recharge in last 30 days at user level (in Indonesian Rupiah)	
16	cnt_ma_rech90	Number of times main account got recharged in last 90 days	
17	fr_ma_rech90	Frequency of main account recharged in last 90 days	Unsure of given definition
18	sumamnt_ma_rech90	Total amount of recharge in main account over last 90 days (in Indonasian Rupiah)	
19	medianamnt_ma_rech90	Median of amount of recharges done in main account over last 90 days at user level (in Indonasian Rupiah)	
20	medianmarechprebal90	Median of main account balance just before recharge in last 90 days at user level (in Indonasian Rupiah)	
21	cnt_da_rech30	Number of times data account got recharged in last 30 days	
22	fr_da_rech30	Frequency of data account recharged in last 30 days	
23	cnt_da_rech90	Number of times data account got recharged in last 90 days	
24	fr_da_rech90	Frequency of data account recharged in last 90 days	
25	cnt_loans30	Number of loans taken by user in last 30 days	
26	amnt_loans30	Total amount of loans taken by user in last 30 days	
27	maxamnt_loans30	maximum amount of loan taken by the user in last 30 days	There are only two options: 5 & 10 Rs., for which the user needs to pay back 6 & 12 Rs. respectively
28	medianamnt_loans30	Median of amounts of loan taken by the user in last 30 days	
29	cnt_loans90	Number of loans taken by user in last 90 days	
30	amnt_loans90	Total amount of loans taken by user in last 90 days	
31	maxamnt_loans90	maximum amount of loan taken by the user in last 90 days	
32	medianamnt_loans90	Median of amounts of loan taken by the user in last 90 days	
33	payback30	Average payback time in days over last 30 days	
34	payback90	Average payback time in days over last 90 days	
35	pcircle	telecom circle	
36	pdate	date